blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/inertiajs/inertia/discussions/new?category=ideas
    about: 'Suggest any ideas you have using our discussion forums.'
  - name: Help
    url: https://github.com/inertiajs/inertia/discussions/new?category=help
    about: 'If you have a question or need help, ask a question on the discussion forums.'
  - name: 'Laravel Adapter Issue'
    url: https://github.com/inertiajs/inertia-laravel
    about: 'For Laravel adapter issues, suggest changes on our (server-side) Laravel adapter repository.'
  - name: Documentation Issue
    url: https://github.com/inertiajs/inertiajs.com
    about: 'For documentation issues, suggest changes on our documentation repository.'
